### ISSUE TITLE
Projeto mal Programado!

### ISSUE THREAD

**Issue by tiagoryandev** [tgkevinbr/Discord-Bot-Source#2]
### :lock: Segurança:

Esse projeto que você desenvolveu está com uma péssima qualidade, em relação a **Estruturação** e **Segurança**, como foi mostrado no arquivo principal, você liberou o acesso mais importante de sua aplicação, o **Token de Acesso**, e isso é o pior erro de um programador iniciante, você precisa aplicar um método de **Variáveis Locais** no seu projeto, e criar um arquivo `.env` no seu projeto, assim o arquivo deve ficar desse modo:

:gear: Modo de Uso:
```env
TOKEN=SEU_TOKEN
```  
:computer: Como fazer a Busca do Token:
```js
client.login(process.env.TOKEN); // Faz a exportação do seu Token dentro do arquivo .env
```

Desse modo você pode esconder do seu projeto o **Token de Acesso**, mais não significa que ele não será mostrado no repositório do seu **Github**, antes de fazer o envio dos seus arquivos para o repositório, você deve adicionar o seu arquivo `.gitignore` o arquivo `.env`, assim que você fazer o **Push**, você não vai enviar o arquivo `.env` para o repositório.

### :wrench: Estruturação:

Já vimos como ter mais segurança a criação do seu projeto, agora vamos entrar no contexto de estruturação do seu projeto, onde seu projeto mais peca. Primeiramente o seu arquivo principal `index.js`, está com **2 Eventos Repetidos**, que são emitidos pela ação de **Mensagem**, onde possui varias condições que foram implementadas de forma desnecessárias no seu arquivo principal.

Em relação aos comandos que são apenas **1**, o meio de criação não foi muito pensado para os servidores, onde possam ser usados de forma má intencionada, como emitir informações pessoais. Melhore isso para que possa ser mais adequado ao uso de servidores grandes.

## `2º` **|** Considerações Finais:

Eu não sei se você é iniciante na linguagem **JavaScript**, mais caso não seja você não aplicou os conceitos basicos acima, e isso torna você um programador inexperiente na comunidade brasileira. Isso é ruim? Não, pois ajuda mais no aprendizado do programador, e espero que futuramente você melhore mais! :heart: 

Espero que leia isso e Obrigado! :+1: 

:bird: **Twitter:**: [@TiaGoiNsaNy](https://twitter.com/TiaGoiNsaNy)
:email: **Discord**: `TiaGoiNsaNy#9903`

**Comment by zluckkyus** [comment]
Obrigado pelas dicas! Sobre o .env a pessoa pode configurar do jeito que
quiser o bot pois é uma source. Sobre os eventos de message que está
repitdo. Eu tentei fazer algo organizado, porém sou iniciante em javascript
então falhas acontecem.

Em sex, 19 de mar de 2021 18:46, TiaGoiNsaNy ***@***.***>
escreveu:

**Comment by zluckkyus** [comment]
A tbm o token da minha aplicação foi regenerado eu esqueci de remover.

Em sex, 19 de mar de 2021 18:46, TiaGoiNsaNy ***@***.***>
escreveu:

**Comment by tiagoryandev** [comment]
# Sucesso no seu Aprendizado! :heart:
